### ISSUE TITLE
希望添加修改app主题颜色的功能

### ISSUE THREAD

**Issue by skyhx** [dyhkwong/SagerNet#37]
希望添加修改app主题颜色的功能

**Comment by jhli999** [comment]
> 希望添加修改app主题颜色的功能

从0.10.12还是13就可以更改主题颜色了呀

**Comment by skyhx** [comment]
> > 希望添加修改app主题颜色的功能
> 
> 从0.10.12还是13就可以更改主题颜色了呀

不好意思，我还用的老版，我以为没有这个功能呢。谢谢了
